### ISSUE TITLE
update example mode output file(s) to our format

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/example-complex-scenario-hub#6]
In looking at [this file](https://raw.githubusercontent.com/Infectious-Disease-Modeling-Hubs/example-complex-scenario-hub/main/model-output/team-model/2022-05-22.csv), I noticed that we'll need to make some minor updates to get it to match the file format that we've landed on. The main thing I noticed is that we will need an `output_type` column with values `"sample"`, and then we could basically rename the current `sample` column to `output_id`.

**Comment by shauntruelove** [comment]
fixed.
