### ISSUE TITLE
Clean up target metadata specification for "prop X" target

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/example-complex-scenario-hub#7]
See current metadata draft [here](https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-scenario-hub/blob/ca61e5eebb8fa72e5c08542cdad33aee40f12618/hub-config/tasks.json#L436-L447).

A couple of minor things to resolve:
- What is a good `target_name` (imagine that this will be used as a label on a plot)
- What is the `target_description` (one-sentence description of the target)
- Is this a weekly step ahead target?
- What are the appropriate `target_units` and `target_type` for a target that is a proportion?

**Comment by LucieContamin** [comment]
Done in [#0b8a4ae](https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-scenario-hub/commit/0b8a4ae4579ffcefa270ce7df681c99ebe0d6234)
